language: node_js

node_js:
  - '10'
  - '12'

cache: npm

install:
  - npm ci
  - npm run build

script:
  - npm run typecheck
  - npm run lint
  - npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep-history: true
  local-dir: public/
  on:
    branch: master
    node_js: '10'
